# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=256),
        ),
    ]
