# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='author',
            field=models.ForeignKey(default='author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0430\u0432\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u0434\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend',
            field=models.ForeignKey(default='friend', on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u0434\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set([('initiator', 'recipient')]),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='first',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='second',
        ),
    ]
